name: Build Binaries
on:
  push:
    paths-ignore:
    - .devcontainer/**
    - .github/**
    - Bootloader/**
    - Copy to SD Card root directory to update/**
    - images/**
    - readme/**
    - '**/*.md'

jobs:
  main:
    name: Build Binaries
    if: github.repository == 'MirakelPrints/BIGTREETECH-TouchScreenFirmware'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio

      - name: Build GD MKS TFT28 V4.0 
        run: platformio run --environment MKS_GD_TFT28_V4_0

      - name: Remove Old Binaries
        run: find "Copy to SD Card root directory to update/" -name '*.bin' -print -delete

      - name: Remove Old Config
        run: find "Copy to SD Card root directory to update/" -name 'config*.ini' -print -delete

      - name: Copy New Binaries
        run: find .pio/build/ -name '*.bin' -exec cp -vf '{}' "./Copy to SD Card root directory to update/" ";"

      - name: Copy New Config
        run: find TFT/src/User/ -name 'config*.ini' -exec cp -vf '{}' "./Copy to SD Card root directory to update/" ";"

      - name: Stage New Binaries
        run: |
          find "Copy to SD Card root directory to update/" -name '*.bin' -exec git add {} \;

      - name: Stage New Config
        run: |
          find "Copy to SD Card root directory to update/" -name 'config*.ini' -exec git add {} \;

      - name: Push
        uses: actions-x/commit@v6
        with:
          email: 125509558+MirakelPrints@users.noreply.github.com
          name: MirakelPrints
          message: üì¶Ô∏è Update MKS_GD_TFT28_V4_0 binary and config
          token: ${{ secrets.TOKEN }}
